### ISSUE TITLE
Support graphql 0.12 style description

### ISSUE THREAD

**Issue by moimael** [apollographql/eslint-plugin-graphql#112]
New schema generated from graphql 0.12 have triple quoted description that breaks this plugin.

Can we have support for it ? Right now I have to strip them using a sed command.

Thanks !

**Comment by jnwng** [comment]
GraphQL 0.12 Support is a little complex due to upstream libraries. Hoping
to cut a new release sometime this week but may have to be a major release.

**Comment by WaldoJeffers** [comment]
Is there anything we can do to help @jnwng ? It's kind of sad to see this plugin breaks because of quotes 😆

**Comment by real34** [comment]
Hi folks! I started a branch at https://github.com/real34/eslint-plugin-graphql/tree/upgrade-graphql but have no idea of what I’m doing… I’ll learn when I will have free time, but if someone wants to take over do not hesitate

**Comment by jnwng** [comment]
this should be addressed by #119 which is a little more holistic and provides some guarantees of the versions we support. it uncovered a couple of bugs in the libraries being used here, but do you mind verifying if that resolves your issues?

**Comment by real34** [comment]
Hi, thanks for your time. I am not sure how I could test it in my project. Could you redirect me to the relevant resources?

I tried to install it using `npm i -D jnwng/eslint-plugin-graphql@jw/graphql-12-13` but ESLint cannot load the plugin. When I look in the code, I do not see the `lib` directory (generated in the prepublish step) neither the `src`.

**Comment by jnwng** [comment]
It’s a branch inside this repo itself, but you’re right it might not be
going through the publish step. Try the jw/graphql-12-13 branch here and
link it locally?

**Comment by jnwng** [comment]
should be resolved as of `eslint-plugin-graphql@2.0.0`

**Comment by WaldoJeffers** [comment]
This is great news, thanks @jnwng 🎉
