### ISSUE TITLE
Missing Github Releases for v2.0.0 & v2.0.1

### ISSUE THREAD

**Issue by cfnelson** [apollographql/eslint-plugin-graphql#142]
**Issue Labels**
- [x] docs

Noticed that the last two releases (v2.0.0 & v2.0.1) are missing from the [github releases](https://github.com/apollographql/eslint-plugin-graphql/releases) page.

Not sure if this was automated in the past?

**Comment by jnwng** [comment]
i've been pushing without the `--tags` flag, thanks for letting me know! they should be there now.
