### ISSUE TITLE
Dummy questions: 

### ISSUE THREAD

**Issue by MichaelSu1983** [apollographql/eslint-plugin-graphql#147]
I install this plugin, and config it as below, but got the following error. 
`1:1  error  Definition for rule 'graphql/template-strings' was not found`

dummy question, am I missing something?

2nd question, it is said this plugin is working for queries embedded in java script files, we have some query inside javascript files, so how do I config the plugin to get it working though?

`
const getFieldDataGraphQlQuery = (issueKey, projectKey) =>
    `query {
        issue(issueIdOrKey: "${issueKey}", latestVersion: true, screen: "view") {
            fields {
                abcccccc
                title
                editable
                required
                autoCompleteUrl
                allowedValues
                content
                renderedContent
                schema {
                    custom
                    system
                }
            }
            id
        }
        project(projectIdOrKey: "${projectKey}") {
            id
            projectTypeKey
        }
    }`;`

.eslintrc.js file looks as below
`   
....
plugins: [
        'prettier',
        'jest',
        'graphql'
    ],
    rules: {
        'graphql/template-strings': ['error', {
            env: 'literal',
            tagName: 'query {',
            schemaJson: require('./schema.json'),
        }],
....
`

**Comment by jnwng** [comment]
i would confirm that 1) you have `eslint-plugin-graphql` installed in the relevant location in `node_modules`, and that 2) wherever you're running `eslint` from, it has access to that library.

please re-open if you're still having issues with this.

**Comment by lukeaus** [comment]
You can get this error if you miss this:

```
    "plugins": [
      "graphql"
    ]

```

So make sure you this in
