### ISSUE TITLE
Update peerDependencies

### ISSUE THREAD

**Issue by muuvmuuv** [apollographql/eslint-plugin-graphql#221]
When I install this plugin I get `npm WARN eslint-plugin-graphql@2.1.1 requires a peer of graphql@^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.` but the latest graphql I have is 14.2.1...

**Comment by jnwng** [comment]
i believe that we have support for `graphql@14.2.1` as of `eslint-plugin-graphql@^3.0.0`
