### ISSUE TITLE
Lodash vulnerability

### ISSUE THREAD

**Issue by tcoughlin3** [apollographql/eslint-plugin-graphql#223]
There's a high severity vulnerability reported for lodash < 4.17.11. Can we upgrade the lodash dependency for this plugin to 4.17.11 or higher? I'd be happy to create a PR if you'd like me to.

https://snyk.io/vuln/SNYK-JS-LODASH-73638

**Comment by jnwng** [comment]
a PR would be wonderfully helpful, although im curious why Renovate didn't send an update for this...
