### ISSUE TITLE
please clarify maintenance status

### ISSUE THREAD

**Issue by stefanprobst** [apollographql/eslint-plugin-graphql#296]
please clarify the maintainance status of this package. if the project has been abandoned by apollo it would be good to say so in the readme. thanks!

**Comment by jtomaszewski** [comment]
I just discovered https://github.com/dotansimha/graphql-eslint . Probably we should switch to that instead.

(Somehow, I couldn't get the eslint for `*.graphql` files working with this plugin.)

**Comment by pleunv** [comment]
Little bump... Is there any plan to maintain this package any further? Most (if not all) dependencies are way out of date, and there has been no (PR) activity in a very long time.

**Comment by mcmxcdev** [comment]
Guys, check the README of the project, there is a deprecation notice now from a couple of days ago ;)
