### ISSUE TITLE
Cannot find module '@ardatan#1626/fetch-event-source'

### ISSUE THREAD

**Issue by binary64** [apollographql/eslint-plugin-graphql#309]
I am suddenly getting `Failed to load plugin 'graphql' declared in 'apps/web/.eslintrc.js » ../../.eslintrc.js': Cannot find module '@ardatan#1626/fetch-event-source'` on my CI and IDE. Am using `"eslint-plugin-graphql": "4.0.0"`

**Comment by binary64** [comment]
I'm a bit stuck...

If I restore a yarn.lock from a few days ago, everything works fine. If I do a 'yarn', it's still fine. But if I delete my yarn.lock, then 'yarn', it all crashes with this problem.

**Comment by caramcc** [comment]
I hit the same issue for a different missing module when I was running `yarn install --ignore-optional`. Allowing the optional dependencies to be installed resolved this for me, so I suspect optional dependencies are being expected.

**Comment by binary64** [comment]
I upgraded everything (yarn upgrade-interactive --latest) and the problem seems to have gone away.
