### ISSUE TITLE
Support for reading introspection schema.json file and validate this with response.gql file locally

### ISSUE THREAD

**Issue by lavi2088** [apollographql/eslint-plugin-graphql#43]
Hello Guys, 
I ran into issue where I need to validate schema,json and response.gql file . I can see this lib has capability of doing this. Really appreciate if someone can help me with snippet to run the package. 
Thanks in advance.

**Comment by jnwng** [comment]
if i understand what you're asking for, you want to be able to use this linter to lint arbitrary `.gql` files, correct? if so, [this section may help you](https://github.com/apollographql/eslint-plugin-graphql#graphql-literal-files).

if that wasn't what you were looking for, please feel free to re-open this issue!
