### ISSUE TITLE
Question: Can I somehow use this plugin to check  .ts files?

### ISSUE THREAD

**Issue by tgjorgoski** [apollographql/eslint-plugin-graphql#46]
Hi,
This works perfectly for me in javascript files, but I wonder if it can also be configured to check typescript files also.
Thanks

**Comment by stubailo** [comment]
I've heard there are ways to use ESLint with TypeScript, but haven't tried them. Want to give it a shot and report back how it goes? https://github.com/eslint/typescript-eslint-parser

There's also an Apollo code generator that will give you typed query results here: https://github.com/apollographql/apollo-codegen

**Comment by tgjorgoski** [comment]
Thanks, I just tried the parser, but seems it is not there yet, the eslint-graphql-plugin is throwing exceptions.
