### ISSUE TITLE
Support .eslintrc.json?

### ISSUE THREAD

**Issue by leethree** [apollographql/eslint-plugin-graphql#58]
Is JSON format for ESlint config supported? It looks like `schemaJson` doesn't support file paths.

**Comment by stubailo** [comment]
It's not supported, but perhaps it could be! Any reason you can't just use `.js` instead?

**Comment by leethree** [comment]
Our existing project uses `.eslintrc.json` and we don't feel comfortable introducing dynamic code (e.g. `require(...)`) into a config file. But I got it working with the `schemaJsonFilepath` config.

```json
{
  "plugins": [
    "graphql"
  ],
  "rules": {
    "graphql/template-strings": ["error", {
      "env": "apollo",
      "schemaJsonFilepath": "./data/schema.json"
    }]
  }
}
```

**Comment by stubailo** [comment]
Looks like it's solved then, please send a PR if the schemaJsonFilepath option was too hard to find!

**Comment by WickyNilliams** [comment]
Sorry to jump on an old issue... 

We have our schema in a separate repo/package to our client, as it is shared between a number of apps. Is there some way to use this in a JSON config? If we were to use a JS module the config would look like this:

```js
 "graphql/template-strings": ["error", {
  "env": "apollo",
  "schemaString": require("my-graphql-schema") // whatever the npm module may be
}]
```

But I would prefer to use JSON for the config

**Comment by jnwng** [comment]
@WickyNilliams you can use the `schemaJsonFilepath` argument and pass in the path to the schema if you need: https://github.com/apollographql/eslint-plugin-graphql/tree/93151ab47e069e13d95c7c7545ec1a82c3cc091b#example-config-for-apollo

**Comment by WickyNilliams** [comment]
@jnwng but my schema is a string (defined in SDL) and coming from npm?

**Comment by jnwng** [comment]
ah, sorry. you can't use `require` statements in JSON, right? so i think you'll want to just convert the  `.eslintrc` file to be an `.eslintrc.js` file instead. 

alternatively you can add support in `eslint-plugin-graphql` for another option which is a module library name that gets resolved under the hood. its certainly not unprecedented given that most `eslint` imports happen via string, but it does mean a little bit of work to get that to work properly here. it doesn't currently happen out of the box.

(you could also try using the relative path to the schema that's in node_modules like `schemaJsonFilepath: 'node_modules/some-foo-library/bar.json'`. `schemaJsonFilepath` currently does not support SDL)
