### ISSUE TITLE
Support for GraphQL IDL schema file

### ISSUE THREAD

**Issue by bessey** [apollographql/eslint-plugin-graphql#59]
Feature suggestion: the linter, unlike graphql-tool’s `makeExecutableSchema`, relies not on a GraphQL IDL file, but instead on the much longer introspection query file.

I version control my schema with each client, so there test suites can be run against a static target, it _would be nice (tm)_ if I didn't need to do any legwork to convert my IDL to the JSON format.

**Comment by bessey** [comment]
Per @jnwng's reply on Slack:

>  i think the output of [`buildSchemaFromTypeDefinitions`](https://github.com/apollographql/graphql-tools/blob/d78d6f6a9ac6dc0c346c0eb58dc0cff2761f1ea2/src/schemaGenerator.ts#L142)  could be used to translate the IDL back to the schema we can parse with the `graphql` library (which we’re using under the hood)

**Comment by jnwng** [comment]
definitely, i like this since we can generate the executable schema. would happily accept a PR to this effect!

**Comment by stubailo** [comment]
Context: When this tool was first introduced, the IDL actually didn't exist! So adding it as an option alongside the introspection result would be awesome.
