### ISSUE TITLE
KnownFragmentNames and NoUnusedFragments across GraphQL file imports

### ISSUE THREAD

**Issue by PepperTeasdale** [apollographql/eslint-plugin-graphql#69]
I’m having some issues getting the `#import` statements to work in my `.graphql` literal files. Given three files:
src/containers/PolicyReportContainer/policyReportQuery.graphql :
```
#import "components/StatusPanel/StatusPanelPolicyReport.graphql"
#import "components/PolicyPanel/PolicyPanelPolicyReport.graphql"

query PolicyReport($policyReportId: ID!) {
  carrier_policy_report(id: $policyReportId) {
    ...StatusPanelPolicyReport
    ...PolicyPanelPolicyReport
  }
}
```

src/components/PolicyPanel/PolicyPanelPolicyReport.graphql :
```
fragment PolicyPanelPolicyReport on CarrierPolicyReport {
  id
  foo
  bar
}
```

and src/components/StatusPanel/StatusPanelPolicyReport.graphql :
```
fragment StatusPanelPolicyReport on CarrierPolicyReport {
  id
  baz
}
```

I get these errors from the linter:
```
./src/components/PolicyPanel/PolicyPanelPolicyReport.graphql
  1:0  error  Fragment "PolicyPanelPolicyReport" is never used  graphql/template-strings

./src/components/StatusPanel/StatusPanelPolicyReport.graphql
  1:0  error  Fragment "StatusPanelPolicyReport" is never used  graphql/template-strings

./src/containers/PolicyReportContainer/policyReportQuery.graphql
  11:12  error  Unknown fragment "StatusPanelPolicyReport"  graphql/template-strings

✖ 3 problems (3 errors, 0 warnings)
```

looking through the issues on github, I’m not seeing anyone else with this specific problem and others seem to be using the ‘literal’ option without these kinds of issues. any thoughts? using a simple `.eslintrc.js` :
```
module.exports = {
  "parser": "babel-eslint",
  "rules": {
    "graphql/template-strings": [2, {
      env: 'literal',
      schemaJson: require('./schema.json')
    }]
  },
  "plugins": ["graphql"]
}
```

Per a conversation with @stubailo on Slack, I will submit a PR that removes the KnownFragmentNames and NoUnusedFragments from the default rules in the literal env. Would be interested in contributing a real fix, but will need some guidance.

**Comment by stubailo** [comment]
Should be fixed!

Since this plugin looks at every file separately, I don't think following the actual imports will be easy to do. Perhaps once we unify some of the code generation/analysis tools with apollo-codegen that could be included, but I feel like it would be overkill for this ESLint plugin. I think you don't want something that runs on every code edit loading a bunch of files etc.

Are there examples of other ESLint plugins out there that follow imports and analyze code across multiple files?

**Comment by PepperTeasdale** [comment]
Yeah, what you're saying makes sense to me. I haven't tested yet, but does this have any implications for the required variables rule? I'll start following along the codegen project, as these are definitely nice checks to have. Thank you!

**Comment by grydstedt** [comment]
Running into this. We're migrating to Apollo from Relay and having something like this:
```
Jobs.js
const query = gql`
  query JobsQuery {
      jobs {
        id
        ...JobItemJob
      }
    }
  ${JobItem.fragments.job}
`;

JobItem.js
static fragments = {
    job: gql`
      fragment JobItemJob on Job {
        id
        text
      }
    `
  };
```

Trying to catch when someone accidentally changes the fragment name in JobItem.js and breaks runtime. Is this possible through some sort of static analysis? Or is there a good pattern to put the fragment name in the child so it doesn't leak to the parent?
