### ISSUE TITLE
Array.prototype.includes is not a function in node versions <= 5

### ISSUE THREAD

**Issue by PepperTeasdale** [apollographql/eslint-plugin-graphql#72]
In node V5, the `Array.prototype.includes` is hidden behind the `harmony` flag and not supported in earlier versions. In node `5.4.1`, using the `literal` env throws:
```javascript
TypeError: (0 , _lodash.keys)(...).map(...).includes is not a function
```

The entry point to the tests have the line:
```
require('babel-polyfill');
```

According to the [node docs](https://babeljs.io/docs/usage/polyfill/):
> This will emulate a full ES2015+ environment and is intended to be used in an application rather than a library/tool.

Using [transform-runtime](http://babeljs.io/docs/plugins/transform-runtime/) is recommended for library code, which will not include instance methods and built-ins and pollute the global scope.

Per a slack conversation with @stubailo , I will be furnishing a pull request to solve this.

**Comment by jnwng** [comment]
closed by #73
