### ISSUE TITLE
Multiple schemas and tagName

### ISSUE THREAD

**Issue by yuricamara** [apollographql/eslint-plugin-graphql#84]
Hi,

From readme:

```
module.exports = {
  parser: "babel-eslint",
  rules: {
    "graphql/template-strings": ['error', {
      env: 'apollo',
      tagName: 'FirstGQL',
      schemaJson: require('./schema-first.json')
    }, .... ,
  plugins: [
    'graphql'
  ]
}
```

Where does tagName come from? I thought It was a config in graphql-tag but I found nothing in the repo about it.

From graphql-tag readme:
```
import gql from 'graphql-tag';
 
const query = gql`
  {
    user(id: 5) {
      firstName
      lastName
    }
  }
`
```
For me the tagName here is gql and it seeems that it is not possible to change!!!

I have more than one schema and I am using Apollo Client with Angular 4!

Thanks!

**Comment by stubailo** [comment]
With ES2015 imports you control the name:

```js
import myGql from 'graphql-tag';
 
const query = myGql`
  {
    user(id: 5) {
      firstName
      lastName
    }
  }
`
```

**Comment by yuricamara** [comment]
It wasn´t working because of other issue. Thanks!
