### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by beam-billie** [apollographql/eslint-plugin-graphql#96]
Does this package work for typescript? Alternatively, is there an equivalent for typescript?

**Comment by HideDev** [comment]
+1!  Yes support for tslint it would be great

**Comment by HideDev** [comment]
I found an experimental version https://github.com/arvitaly/tslint-plugin-graphql

**Comment by trsh** [comment]
@listepo-alterpost do you use it? It's working?

**Comment by trsh** [comment]
But yeah, definitely, after introducing Apollo angular we need lint for ts.

**Comment by trsh** [comment]
Btw. This is what I did as workaround for now.

a) installed eslint parallel tslint
b) configured eslint as required by this Plugin
c) The only rule is "graphql/template-strings" for eslint, for others I use tslint 
d) Put all my gql declarations in a separate files *.gql.ts and export them as constants
e) Created a script in package.json "eslint --ext .gql.ts ."

OK!

**Comment by tsaiDavid** [comment]
Just wondering if there were any thoughts about getting `tslint` support?

**Comment by benjie** [comment]
You can use `eslint-plugin-graphql` with TypeScript by using `@typescript-eslint/parser`. An article like this might help: https://medium.com/@oliver.grack/using-eslint-with-typescript-and-react-hooks-and-vscode-c583a18f0c75

**Comment by sampsonjoliver** [comment]
As per https://github.com/palantir/tslint/issues/4534 TSLint is planned to be deprecated in favour of ESLint and `@typescript-eslint`.

The way forward for this is absolutely to use eslint with parser `@typescript-eslint/parser` and plugins `eslint-plugin-graphql` and `@typescript-eslint`.

**Comment by Guillaume-Mayer** [comment]
I would like that too (gql tag validation, for schema).

**Comment by benjie** [comment]
As TSLint is being deprecated and this plugin works with ESLint thanks to `@typescript-eslint/parser` I believe this issue can be closed.
